org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=3
systemProp.file.encoding=utf-8

###########################
#### Gradle properties ###
#########################
group=me.srrapero720

##########################
#### Mod information ####
########################
modid=watervision
modname=WaterVision
# The mod version. See https://semver.org/
modversion=0.2.0-alpha
modauthors=SrRapero720
modcredits=Powered by WaterMedia
moddesc=Record, Watch and Broadcast videos in game
license=PolyForm Strict License 1.0.0
github=SrRapero720/watervision

#####################
#### Enviroment ####
###################
javaversion=17
modloader=FABRIC
modloadershort=FB
minecraftversion=1.20.1
minecraftrange=>=1.20.1
fabricloaderversion=0.16.9
fabricversion=0.92.1+1.20.1
fmlrange=[47,)
mappingschannel=parchment
mappingsversion=2023.09.03
modrinthid=dGGbEGoV
curseforgeid=1167473

#######################
#### Dependencies ####
#####################
 watermediaversion=2.1.30
 watermediarange=>=2.1.30

#######################
#### Mixins config ###
#####################
mixin_version=0.8.5
mixin_fabric_version=0.12.5
mixinextra_version=0.3.5
mixinextra_version_range=[0.3.5,)
mixin_file_suffix=mixin.json
mixin_refmap_suffix=mixin-refmap.json